language: python
python:
  - "3.6"
  - "3.7"

# command to install dependencies
install:
  - "pip install pipenv --upgrade-strategy=only-if-needed"
  - "pipenv install --dev"

# command to run the dependencies
script:
  - "pytest"
