# travis use trusty by default
dist: xenial

language: python
python:
  - 3.6
  - 3.7
  - 3.8

# command to install dependencies
install:
  - pip install pipenv --upgrade-strategy=only-if-needed
  - pipenv install --dev

# command to run the dependencies
script:
  - black responder tests setup.py --check
  - pytest
